### ISSUE TITLE
Use $http instead of $resource to integrate Angular in Tutorial #3

### ISSUE THREAD

**Issue by ghost** [johnstonbl01/clementinejs-fcc#9]
I tried to write Tutorial #3 over my Tutorial #2 code, integrating AngularJS with Mongoose and Passport.  I think I've solved the issue, but to help others avoid the pit I fell into, I spent Christmas Eve bashing my head as to why the code written for Tutorial #2, $resource("/api/clicks") wasn't working in Tutorial #3 as $resource("/api/:id/clicks").

In clickController.client.js, $resource("/api/:id", {id: "@id"}) worked for the $scope.getClicks() function, but in userController.client.js and the other $scope functions, I received the error "http://gbhojraj.c9.io/api/clicks not found".  The :id field disappeared in the request URL.

I'm not sure why $resource was able to access the data in $scope.getClicks() and not in POST or any other scopes, but rewriting the code with $http.get("/api/:id").then(function(result){...}; works!

**Comment by johnstonbl01** [comment]
@gbhojraj The Passport tutorial isn't meant to be followed after the Angular tutorial, so I'm not surprised you ran into issues. This is because the Angular way to handle data requests (like AJAX) are typically done through a service / provider / factory. If you want to use Angular for the FCC base jumps, I actually recommend going through the first tutorial, followed by the Passport tutorial and then integrating Angular.

I do realize that the order of the tutorials isn't 100% clear, and this is on my list of things to address in the next 6 months. In the meantime, if you've got questions about Angular & Clementine, feel free to message me on Gitter.
